stages:
  - build
  - release
  - deploy

variables:
  IMAGE_NAME: "hamzablr/mini-projet-gitlab"
  IMAGE_TAG: "v1"
  HOST_PORT: 80
  CONTAINER_PORT: 80
  SERVER_IP: "192.168.56.10"
  SERVER_USERNAME: "ubuntu"

Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker save -o mini-projet-gitlab.tar $IMAGE_NAME:$IMAGE_TAG
  artifacts:
    paths:
      - mini-projet-gitlab.tar

Release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker load -i mini-projet-gitlab.tar
    - docker push $IMAGE_NAME:$IMAGE_TAG

Deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh ansible bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - cd infra/ansible
    - ansible-playbook -i inventory.ini deploy.yml